services:
  db:
    image: mysql:8.0
    container_name: pfe-mysql
    restart: always
    environment:
      MYSQL_DATABASE: gestion_notes
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3306"   # pour éviter le conflit avec MySQL local
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pfe-network

  app:
    image: ghcr.io/elmehdi19/plateforme_pfe:latest
    container_name: pfe-app
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/gestion_notes?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: 12345
    ports:
      - "8081:8080"   # ← changement ici
    networks:
      - pfe-network

volumes:
  mysql_data:

networks:
  pfe-network:
    driver: bridge