services:
  app:
    build: .
    container_name: pfe-app
    restart: always
    environment:
      DB_URL: jdbc:mysql://host.docker.internal:3306/gestion_notes?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: 12345
    ports:
      - "8081:8080"