services:
  app:
    image: pfe-local
    container_name: pfe-backend
    restart: always
    environment:
      DB_URL: jdbc:mysql://143.110.190.40:10546/defaultdb?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: avnadmin
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"